//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoApp.ClientsView.TableDetails
{
    public partial class TableDetails
    {
        protected global::System.Web.UI.WebControls.Panel pnlDetails;
        protected global::System.Web.UI.WebControls.Image imgMain;
        protected global::System.Web.UI.WebControls.Literal litLocationBadge;
        protected global::System.Web.UI.WebControls.Literal litTableNumber;
        protected global::System.Web.UI.WebControls.Literal litCapacity;
        protected global::System.Web.UI.WebControls.Literal litLocation;
        protected global::System.Web.UI.WebControls.Literal litLocationDesc;
        protected global::System.Web.UI.WebControls.Literal litCapacityDesc;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Panel pnlSimilarTables;
        protected global::System.Web.UI.WebControls.Repeater rptSimilar;
    }
}