//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestoApp.ClientsView.Items
{
    public partial class ItemDetails
    {
        protected global::System.Web.UI.WebControls.Panel pnlDetails;
        protected global::System.Web.UI.WebControls.Image imgMain;
        protected global::System.Web.UI.WebControls.Literal litCategory;
        protected global::System.Web.UI.WebControls.Literal litItemName;
        protected global::System.Web.UI.WebControls.Literal litCurrency;
        protected global::System.Web.UI.WebControls.Literal litPrice;
        protected global::System.Web.UI.WebControls.Literal litOrigin;
        protected global::System.Web.UI.WebControls.Literal litDescription;
        protected global::System.Web.UI.WebControls.Literal litIngredients;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Panel pnlSimilarItems;
        protected global::System.Web.UI.WebControls.Repeater rptSimilar;
    }
}
